name: Ruby

on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.0']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.0

    - name: Install dependencies
      run: |
        yarn install

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Run seeds
      run: make seed
